---
openstack_instances: 
  - instance_name: app1
    group: app_servers
    deployment: QA
    security_group_name: apps
    image: "{{ _server_image | default('rhel-7.6') }}"

  - instance_name: app2
    group: app_servers
    deployment: dev
    security_group_name: apps
    image: "{{ _server_image | default('rhel-7.6') }}"

  - instance_name: db
    group: database_servers
    deployment: dev
    security_group_name: db
    image: "{{ _server_image | default('rhel-7.6') }}"

  - instance_name: frontend
    group: load_balancers
    deployment: dev
    security_group_name: frontend
    image: "{{ _server_image | default('rhel-7.6') }}"
...
